version: '3'

services:
  #nginx
  nginx-service:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-scraper

  #php
  php-service:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - my-scraper

  #mysql
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - my-scraper

  #redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - my-scraper

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - '15672:15672'
    restart: always
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

networks:
  my-scraper:
    driver: bridge
    external: true